// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqsnetliooavvupvogia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xc25ldGxpb29hdnZ1cHZvZ2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjI5MjEsImV4cCI6MjA3NDYzODkyMX0.H04K6ZwH4wIr7SvOTmQq0qVuvjwmX8T3CkJ_Is9n5Ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});